# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/dioi/root";
      fsType = "ext4";
    };

  fileSystems."/root/keys" =
    { device = "/dev/sdb2";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/data/home";
      fsType = "ext4";
    };

  fileSystems."/var" =
    { device = "/dev/data/var";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/data/nix";
      fsType = "ext4";
    };

  fileSystems."/root/mnt" =
    { device = "/dev/dioi/mnt";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
